"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['EC2ICManager.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'icon.icns',   # Optional: your .icns file for a Mac icon
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
